-- 定义一个公共的autoReplies
CommonAutoReplies = {
  { keyword = "发布了", reply = "好的" },
  { keyword = "发给你了", reply = "好的" },
  { keyword = "发了", reply = "好的" },
  { keyword = "发你了", reply = "好的" },
  { keyword = "已发", reply = "好的" },
  { keyword = "发过", reply = "好的" },
  { keyword = "下了", reply = "好的" },
  { keyword = "免费", reply = "对的，直接下单就行～" },
  { keyword = "发谁", reply = "直接给这个号下单就行" },
  { keyword = "发给谁", reply = "直接给这个号下单就行" },
  { keyword = "名字", reply = "直接给这个号下单就行" },
  { keyword = "这个号", reply = "直接给这个号下单就行" },
  { keyword = "这号", reply = "直接给这个号下单就行" },
  { keyword = "id", reply = "直接给这个号下单就行" },
  { keyword = "三星", reply = "要三星材料三星公函三星美化哈～" },
  { keyword = "3星", reply = "要三星材料三星公函三星美化哈～" },
  { keyword = "匠人", reply = "匠人我也没有，需要自己百度一下怎么搞" },
}
